### ISSUE TITLE
IngressClass

### ISSUE THREAD

**Issue by BaeKY** [BaeKY/k8s-cicd#5]
## 개요
- v1.0.0 이상의 ingress-nginx-controller 사용시 IngressClass 가 필수사항이 되었음.

## TODO
- [x] [What is an "IngressClass" and why is it important for users of "ingress-nginx-controller" now](https://kubernetes.github.io/ingress-nginx/#what-is-an-ingressclass-and-why-is-it-important-for-users-of-ingress-nginx-controller-now)
- [x] Apply to #3

**Comment by BaeKY** [comment]
## Ingress에서 IngressClassName 사용
- 다음과 같이 Ingress Manifest에서 어떤 IngressClass를 사용할지 명시한다
```YAML
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/name: svelte-example
  name: svelte-example
  namespace: apps
spec:
  ingressClassName: nginx           # 여기 추가됨
  rules:
    - host: svelte-example.baeky-test.com
      http:
        paths:
          - backend:
              service:
                name: svelte-example
                port:
                  number: 80
            path: /
            pathType: Prefix

```
